# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'develop'
target 'week4-1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week4-1

end
